### ISSUE TITLE
Plugin config for jupyter path

### ISSUE THREAD

**Issue by quan-nh** [clojupyter/lein-jupyter#3]
Is it possible to have a configuration for `jupyter` path. I have a jupyter install from anaconda, but I don't want to export it globally.

**Comment by didiercrunch** [comment]
Sure it is!  Which system are you working on (mac, linux, windows)?

**Comment by didiercrunch** [comment]
Actually, can you give me more info about your system and what you would
expect as a "user experience".  Do you have the "conda" command available
globally?

In the meanwhile, you can set your PATH environment to include jupyter.

Cheers,

Didier

**Comment by quan-nh** [comment]
Sorry to not make it clear.

Yes, I know I can `export PATH=$PATH:<path-to-jupyter-dir>` before run `lein jupyter <task>` to resolve this issue.

But on my machine, it's inside anaconda3 & I don't want to export that conda path globally (by setting in `.bashrc`, `.bash_profile`, etc.), since I have another python2 env...

And I'm a bit lazy to set PATH environment each time running `lein jupyter ..`, so I think a configuration from plugin itself could be helpful. Plugin may support to add explicit jupyter path, something like this in `project.clj` file:

```clj
:plugins [[lein-jupyter "0.1.8"]]

:jupyter-path "path/to/jupyter"
```
If it's not defined, the default global jupyter will be used.

**Comment by didiercrunch** [comment]
Morning tentamen,

I have added the new feature this morning (V0.1.9).  You can now add `:jupyter-options {:jupyter-path "PATH_TO_JUPYTER"}` to your project.clj file.  If you wish to add environment variables to the path, you will need to do it on the project.clj side using something like https://stackoverflow.com/questions/30985714/how-to-reference-environmental-variable-or-home-dir-in-project-clj .  I believe we should add path expansion but I do not know how to do it in the most clojurian way.

thanks for using lein-jupyter!

cheers,

didier

**Comment by quan-nh** [comment]
yeah, thanks for your great work!
