### ISSUE TITLE
document the python3 requirement

### ISSUE THREAD

**Issue by gonewest818** [clojupyter/lein-jupyter#5]
at least until/unless python2 is also supported.  thanks-

**Comment by didiercrunch** [comment]
I have added support for python2 on my box but I need to test it before deployment.   I should be able to achieve the testing and deployment tonight.

cheers,

didier

**Comment by didiercrunch** [comment]
I have uploaded the python2 compatibility patch to clojars in version `0.1.10`. 

Many thanks for speaking out about the bug.

didier
