### ISSUE TITLE
Support for returning markdown

### ISSUE THREAD

**Issue by bbss** [clojupyter/lein-jupyter#6]
For python it's possible to return markdown directly as a result, I would love this to work for the clojure kernel as well. 

I'm using lein-jupyter for documentation of a project:
https://bbss.github.io/cljsc2/

Some problems I encountered was manually adding markdown invoked a triggerhappy html sanitizer that removes attributes (such as src on <video>). For that notebook to display a video I had to manually remove the sanitizer from the jupyter JS.

My assumption is going through the right API such as for python will not invoke the same sanitizer.

I am spending some time to figure out how to achieve this for lein-jupyter. Any pointers would be greatly appreciated @didiercrunch

**Comment by didiercrunch** [comment]
(From my mobile phone)

This is a great idea!  The main place to change is clojupyter and not
lein-juoyter.  https://github.com/roryk/clojupyter/blob/
master/src/clojupyter/misc/display.clj is the file you are looking for.
The problem you will face is to build lein-jupyter with your custom
clojupyter.  I should add documentation about it.

I cannot look at the user experience the python kernel provides right now.
I am currently in a week off and tomorrow is my "computer day"!  I'll take
the time to implement this feature.

Many thanks for opening the issue.

Didier.

**Comment by didiercrunch** [comment]
And your project is amazing!  Nothing under outstanding.  I'll try it out
tomorrow.

**Comment by didiercrunch** [comment]
I have open an issue for that one:  https://github.com/roryk/clojupyter/issues/47

**Comment by didiercrunch** [comment]
I have release a new version of lein-jupyter that uses a new version of clojupyter.  You can see the code change at https://github.com/roryk/clojupyter/issues/47 .

In a similar fashion than html, to print mardown you can use the bellow snippet.

~~~
(require '[clojupyter.misc.display :as display])
(display/make-markdown "# This is a title")
~~~

Please, tell me if it fixes your problem.  Otherwise, I'll need more information about what you need.

cheers,

didier

**Comment by bbss** [comment]
Woah awesome, such a quick turnaround! Went to fast for me to notice hahah ⚡️. Thanks a million.

This saves me a ton of time in manually having to copy paste. Closing as this works for me.
